export const searchWrapper: string
export const searchInputWrapper: string
export const searchIconWrapper: string
export const searchInput: string
export const searchFilterWrapper: string
export const notLoggedInHeaderWrapper: string
export const headerLeftSide: string
export const headerRightSide: string
export const headerRightNotificationIcon: string
export const headerRightDropDownWrapper: string
export const headerRightProfileImage: string
export const headerRightDropDownContent: string
export const headerRightDropDownContentItem: string
