export const profileLabelInputWrapper: string
export const profileLabel: string
export const verifiedMark: string
export const profileUnEditableValue: string
export const profileInput: string
export const addNewButton: string
export const profilePhoneNumber: string
export const profileRadioButton: string
export const profileDateInput: string
