export const eventDetailContainer: string
export const eventMainHead: string
export const eventWrapper: string
export const eventDescription: string
export const eventInfo: string
export const webinarAvailability: string
export const takeAways: string
export const teamSection: string
export const cardSection: string
export const card: string
export const cardInfo: string
export const cardOverlay: string