export const wrapper: string
export const scheduleSection: string
export const inputFieldWrapper: string
export const inputFieldStyle: string
export const customFileUpload: string
export const progressBarSection: string
export const progressBarDivision: string
export const progressBarStyle: string
export const stepInfo: string
export const buttonContainer: string
export const formStyle: string
export const timeZoneStyle: string
export const executionInput: string
export const moderatorInput: string
export const speakerInput: string
export const addSpeakerButton: string
export const badge: string
export const joinEventSection: string