export const eventCarouselWrapper: string
export const eventCarouselContentWrapper: string
export const eventCarouselTitle: string
export const eventCardWrapper: string
export const notLastCard: string
export const eventCardContentWrapper: string
export const eventCardTitle: string
export const eventCardTag: string
export const eventCardInfoWrapper: string
export const eventCardButtonWrapper: string
export const eventCardDate: string
export const eventCardTagDateWrapper: string
export const eventCardBlur: string
export const mouseActionEnter1: string
export const mouseActionEnter2: string
export const mouseActionEnter3: string
export const mouseActionEnter4: string
export const mouseActionLeave1: string
export const mouseActionLeave2: string
export const mouseActionLeave3: string
export const mouseActionLeave4: string
