export const otpForm: string
export const otpInput: string
export const otpWrapper: string
export const otpError: string
export const codeEntered: string
export const codeError: string
export const otpResendLabel: string
export const otpResendAction: string
export const otpResendDisabled: string
