export const profileEventWrapper: string
export const profileEventCardScrollContainer: string
export const profileEventCardContainer: string
export const profileEventCardWrapper: string
export const profileEventCardLast: string
export const profileEventCardImage: string
export const profileEventCardContentBlur: string
export const profileEventCardContentWrapper: string
export const profileEventCardTagWrapper: string
export const profileEventCardTag: string
export const profileEventCardTitle: string
export const profileEventAddNew: string
