export const modalBackground: string
export const modalContainer: string
export const modalCloseBar: string
export const modalTitle: string
export const modalBody: string
export const modalFooter: string
export const primaryButton: string
export const declineButton: string
export const showModal: string
