export const profileUserContentWrapper: string
export const profileUserContent: string
export const profileUserContentTitle: string
export const profileUserCompanyWrapper: string
export const profileUserCompanyLogo: string
export const profileUserCompanyDetail: string
export const profileUserPreferredSubjectWrapper: string
export const profileUserPreferredSubject: string
export const profileUserAreaOfInterest: string
