export const hostCarouselWrapper: string
export const hostTitle: string
export const hostSubTitle: string
export const hostCarouselContentWrapper: string
export const hostCardWrapper: string
export const notLastHostCard: string
export const hostCardContentWrapper: string
export const hostCarouselContent: string
export const hostCardContentName: string
export const hostCardTitle: string
export const hostCardCompany: string
export const hostCardDescription: string
export const hostCardBlur: string
export const mouseActionEnter1: string
export const mouseActionEnter2: string
export const mouseActionEnter3: string
export const mouseActionEnter4: string
export const mouseActionLeave1: string
export const mouseActionLeave2: string
export const mouseActionLeave3: string
export const mouseActionLeave4: string
