export const uploadWrapper: string;
export const uploadImage: string;
export const uploadButtonWrapper: string;
export const uploadButton: string
export const uploadFileName: string
export const uploadCriteria: string
export const uploadErrorText: string
export const fileInput: string
export const uploadModalBodyStyle: string
export const uploadModalWrapperStyle: string
export const uploadModalContentWrapper: string
export const uploadModalContentHighlight: string
export const uploadModalIcon: string
export const uploadModalLabels: string
export const uploadModalButton: string
